apiVersion: v1
kind: Service
metadata:
  labels:
    app: juice-shop
  name: juice-shop-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    app: juice-shop

